[package]
name = "rustyserver"
version = "0.1.0"
edition = "2021"
authors = ["Thomas <thschleicher@edu.aau.at>"]

publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]