[package]
name = "rustyserver"
version = "0.1.0"
edition = "2021"
authors = ["Thomas <thschleicher@edu.aau.at>"]

publish = false

[dependencies]
serde = {version = "1.0.188", features = ["derive"]}
toml = {version = "0.8.1"}